services:
  juice:
    image: bkimminich/juice-shop:v19.0.0
    ports: [ "3000" ] # origin/backend  is open

  waf:
    image: owasp/modsecurity-crs:3.3.5-nginx-202308071108
    environment:
      BACKEND: "http://juice:3000"
    ports: [ "8080:8080" ] # added waf service with default configuration
    depends_on: [ "juice" ]