services:
  juice:
    image: bkimminich/juice-shop:latest

  waf:
    image: owasp/modsecurity-crs:nginx
    environment:
      BACKEND: "http://juice:3000"
      SERVER_NAME: "localhost"
      PORT: "8080"
    ports:
      - "127.0.0.1:8080:8080"
    depends_on: ["juice"]
    volumes:
      - ./nginx/default.conf:/etc/nginx/templates/conf.d/default.conf.template:ro
